pipeline {
  agent none

  stages{
    stage("build"){
      when{
        changeset "**/vote/**"
      }

      agent{
        docker{
          image 'python:2.7-alpine'
        }
      }

      steps{
        echo 'Compiling vote app'
        dir('vote'){
          sh 'pip install -r requirements.txt'
        }
      }
    }

    stage("test"){
      when{
        changeset "**/vote/**"
      }

      agent{
        docker{
          image 'python:2.7-alpine'
        }
      }
      steps{
        echo 'Running Unit Tests on vote app'
        dir('vote'){
          sh 'pip install -r requirements.txt'
        }
      }
    }

    stage('docker-package'){
      agent any
      when{
        changeset "**/vote/**"
        branch 'master'
      }
      steps{
        echo 'Packaging vote app with docker'
        script{
          docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
            def votetImage = docker.build("stevejeske/vote:v${env.BUILD_ID}", "./vote")
            voteImage.push()
            voteImage.push("${env.BRANCH_NAME}")
            voteImage.push("latest")
          }
        }
      }
    }
  }

  post{
    always{
      echo 'Building multibranch pipeline for vote is completed..'
    }
  }
}
